### PR TITLE
Upgrade projects to .NetStandard2.0

### LINKED ISSUE #31: Move to netstandard 2.0
As we now have the SQL toolkit deployed as a NuGet package, we need to make sure SQL is on net standard 2.0 to be useable in zero-code tools.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #31 

### Test files
Available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FSQL%5FToolkit%2F%2332%2DUpgradeToNetStandard&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b) - there are also other PR test scripts available here if you want to use more than just the one I've produced.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 11931816648

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check versioning
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by adecler — APPROVED** [review]
- Code changes make sense
 -  Compile without problem
 - The SQL adapter still works as expected
 - Other toolkits depending on the SQL adapter like the EmbodiedCarbon toolkit still work fine

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
