### PR TITLE
Added Upsert Command

### LINKED ISSUE #17: Pushing item with ID should update existing item
If pushing an object with an ID, and a push type set to some form of update, then we should check if an existing item with that ID exists and update its data. If an existing item doesn't exist, then insert.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #17 

Test files [available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FSQL%5FToolkit%2F%2318%2DUpsert&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Review by jamesramsden-bh — CHANGES_REQUESTED** [review]
As per our discussion, please implement compatibility with BHoM custom objects.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix copyright headers ref. 4443326918

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Review by jamesramsden-bh — APPROVED** [review]
LGTM

**Pull request merged**
