### PR TITLE
.csproj files fixed

### LINKED ISSUE #34: .csproj files are missing a few bits
#### Description:
As in the title, the most relevant missing point is lack of postbuild on SQL_Adapter, but also `GenerateSerializationAssemblies` as well as copyright etc.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #34

### Test files

See if builds fine

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Bots happy, so I'm happy, for now 😉

**Pull request merged**
